# Generated by Django 2.0.7 on 2018-07-09 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChatServer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=64)),
                ('Password', models.CharField(max_length=256)),
                ('Email', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='LinkUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ChatServer.AppUser'),
        ),
    ]
