# Generated by Django 2.0.7 on 2018-07-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatServer', '0004_auto_20180709_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='Active',
            field=models.CharField(default='No', max_length=4),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Avatar',
            field=models.IntegerField(default=1, max_length=2),
        ),
    ]
