# Generated by Django 2.0.7 on 2018-07-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatServer', '0005_auto_20180711_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Avatar',
            field=models.IntegerField(default=1),
        ),
    ]
